# Generated by Django 2.2.16 on 2022-06-17 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartrecipes',
            name='user',
            field=models.ForeignKey(help_text='Тот, кто добавил рецепт в корзину', on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингредиент', on_delete=django.db.models.deletion.CASCADE, to='cookbook.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='igredients_in_recipe', to='cookbook.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Автор рецепта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиенты для рецепта', related_name='recipes', through='cookbook.RecipeIngredients', to='cookbook.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Тег рецепта', related_name='recipes_by_tag', to='cookbook.Tag', verbose_name='Тег рецепта'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='uniq_name-measurement_unit_pair'),
        ),
        migrations.AddField(
            model_name='favoritrecipes',
            name='recipe',
            field=models.ForeignKey(help_text='Избранный рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='favorit_recipe', to='cookbook.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favoritrecipes',
            name='user',
            field=models.ForeignKey(help_text='Тот, кто добавил рецепт в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='who_added', to=settings.AUTH_USER_MODEL, verbose_name='Добавивший'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartrecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_set_cart_recipes'),
        ),
        migrations.AddConstraint(
            model_name='favoritrecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_set_favorites_recipes'),
        ),
    ]
