# Generated by Django 2.2.16 on 2022-06-15 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20220612_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления, мин.'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Количество ингредиента в рецепте', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиента в рецепте'),
        ),
    ]
