# Generated by Django 2.2.16 on 2022-06-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20220615_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Рецепт в корзину', on_delete=django.db.models.deletion.CASCADE, related_name='cart_recipe', to='cookbook.Recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(help_text='Тот, кто добавил рецепт в корзину', on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины')),
            ],
            options={
                'verbose_name': 'Рецепт в корзине',
                'verbose_name_plural': 'Рецепты в корзине',
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingcartrecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_set_cart_recipes'),
        ),
    ]
