# Generated by Django 2.2.16 on 2022-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20220615_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart_recipes',
            field=models.ManyToManyField(blank=True, help_text='Рецепты в корзине', related_name='shopping_cart_recipes', through='cookbook.ShoppingCartRecipes', to='cookbook.Recipe', verbose_name='Рецепты в корзине'),
        ),
    ]
